// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// Code generated by New-GoModules.ps1; DO NOT EDIT.
// Target: linux-amd64-musl  triple: x86_64-unknown-linux-musl

//go:build cgo && linux && amd64

package driver

// #cgo LDFLAGS: -L${SRCDIR}/native -lazurecosmosdriver -lgcc_eh -lc
// #include "azurecosmosdriver.h"
import "C"
