// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// Code generated by New-GoModules.ps1; DO NOT EDIT.
// Target: linux-arm64-glibc  triple: aarch64-unknown-linux-gnu

//go:build cgo && linux && arm64

package driver

// #cgo LDFLAGS: -L${SRCDIR}/native -lazurecosmosdriver -lgcc_s -lutil -lrt -lpthread -lm -ldl -lc
// #include "azurecosmosdriver.h"
import "C"
