// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// Code generated by New-GoModules.ps1; DO NOT EDIT.
// Target: linux-arm64-musl  triple: aarch64-unknown-linux-musl

//go:build cgo && linux && arm64

package driver

// #cgo LDFLAGS: -L${SRCDIR} -lazurecosmosdriver -lgcc_eh -lc
// #include "azurecosmosdriver.h"
import "C"
