// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// Code generated by New-GoModules.ps1; DO NOT EDIT.
// Target: windows-amd64  triple: x86_64-pc-windows-gnu

//go:build cgo && windows && amd64

package driver

// #cgo LDFLAGS: -L${SRCDIR}/native -lazurecosmosdriver -Wl,-Bstatic -lwinpthread -Wl,-Bdynamic -lkernel32 -lbcrypt -lkernel32 -lntdll -luserenv -lws2_32 -ldbghelp
// #include "azurecosmosdriver.h"
import "C"
