// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// Code generated by New-GoModules.ps1; DO NOT EDIT.
// Target: darwin-arm64  triple: aarch64-apple-darwin

//go:build cgo && darwin && arm64

package driver

// #cgo LDFLAGS: -L${SRCDIR} -lazurecosmosdriver -framework Security -framework CoreFoundation -liconv -lSystem -lc -lm
// #include "azurecosmosdriver.h"
import "C"
